# Site
repository: antoniovmonge/python-developer
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Antonio Vilchez Monge
title: Python Developer
email: antoniovmonge@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: antonio_v_monge
github_username:  antoniovmonge
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: antonio-v-monge
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-pic-brown.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Antonio. 

  I'm a Python developer specializing in Django.

  I love working for companies looking for a more sustainable way of doing things.

  I am skilled in: <mark>Django</mark> <mark>Flask</mark> <mark>PostgreSQL</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Building Materials
        link: github.com/antoniovmonge/build-mat
        # link_text: Project Website
        additional_links:
          # - title:  Building Materials Project
          - icon: fab fa-github
            url: github.com/antoniovmonge/build-mat
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        # quote: >
        #   This Platform helps with decision making. Compare between more than 2000 building materials for a more sustainable construction.
        description: | # this will include new lines to allow paragraphs
          I started this project to apply everything I'm learning about Django. 
          This platform helps designers to choose the best building materials during the design stages. 
          
          The project includes:

          - Advanced user authentication
          - A Content Management System (CMS)
          - Model inheritance to create data models for polymorphic content
          - Complex permissions and roles assigned programmatically to different type of users
          - A RESTful API using Django REST framework
          - A full-text search engine with Django and PostgreSQL
          - Internal Email management to *Contact us* and *Contact the manufacturer*


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 2050 Materials
        link: 2050-materials.com
        # link_text: boringcompany.com
        sub_title: Freelance Python Django Developer
        caption: April 2022 - Present 
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          2050 Materials is a start up that centralizes all sustainability 
          information into a single platform, enabling designers to save time and 
          money at any project stage.
          
          I helped the company to launch the product by:

          - Implementing the User Authentication system
          - Automating the permission and role assignment for the different kind of users 
          and companies (Advanced role/permission management through migrations)
          - Conducted Data Exploration using Jupyter Notebooks and Pandas to
          check data consistency and fixed issues by re-designing the data
          entry processes
          - Fixed database issues using Django migrations


      - layout: left
        title: Minimal Fashion UK
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Intern Python Django Developer
        caption: November 2021 - March 2021
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Minimal was an early-stage Start-Up based in London looking to create a data-driven shopping platform for sustainable fashion.

          During my time as a Python Developer Intern I helped the team by:

          - Designed and prototyped an e-commerce platform using Django
          - Automated the data entry through the integration of several APIs of
          WooCommerce and Shopify partners that used GraphQL saving
          weeks of manual and repetitive work
          - Designed the database after conducting a Data Exploration using
          Jupyter Notebook and Pandas

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Data Science Bootcamp
        caption: 2021 (Three Months Full Time)
        sub_title: Le Wagon - Berlin
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my Bootcamp I learnt to write code following the highest professional standards. 
          Among the new skills I learnt the value and joy of teamwork and handling with tight deadlines. 
          I thoroughly enjoyed my time at the Bootcamp and learnt a lot about a healthy work life balance and the
          power of motivation and passion in a nice team.

          The strong points of the Bootcamp were:
            - Data Science with Python 
            - Data Analytics with SQL, BigQuery, Pandas, Numpy, and Matplotlib
            - Statistics with Scipy, Seaborn and Statsmodels
            - Machine Learning with Scikit-learn
            - Deep Learning with TensorFlow Keras
            - Developing Data Products with Google Cloud Platform, ML Flow, Flask, Heroku and Streamlit.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my other interests and hobbies are:
        - Playing guitar
        - Running
        - Sound Design
        - Video Production
        - Photography

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
